export function translateDynamic(text, locale) {
  if (!text || typeof text !== 'string') return text;
  
  let t = text;

  if (locale === 'hi') {
    t = t.replace(/Round ([\d\.]+) to (\d+) decimal place(s)?\./gi, "$1 को $2 दशमलव स्थानों तक पूर्णांकित करें।");
    t = t.replace(/Round ([\d\.]+) to (\d+) significant figure(s)?\./gi, "$1 को $2 सार्थक अंकों तक पूर्णांकित करें।");
    t = t.replace(/Find the probability of getting (.*) when rolling a fair six-sided die\./gi, "निष्पक्ष पासा फेंकने पर $1 प्राप्त करने की प्रायिकता ज्ञात करें।");
    t = t.replace(/A bag contains (\d+) (.*) and (\d+) (.*)\./gi, "एक बैग में $1 $2 और $3 $4 हैं।");
    t = t.replace(/A car travels at ([\d\.]+) km\/h for ([\d\.]+) hours\. How far does it travel \(in km\)\?/gi, "एक कार $1 किमी/घंटा की गति से $2 घंटे तक यात्रा करती है। यह कितनी दूर यात्रा करती है (किमी में)?");
    t = t.replace(/A train covers ([\d\.]+) km at ([\d\.]+) km\/h\. How long does the journey take \(in hours\)\?/gi, "एक ट्रेन $1 किमी की दूरी $2 किमी/घंटा की गति से तय करती है। यात्रा में कितना समय लगता है (घंटों में)?");
    t = t.replace(/A cyclist rides ([\d\.]+) km at ([\d\.]+) km\/h then ([\d\.]+) km at ([\d\.]+) km\/h\. Find the average speed \(to 2 d\.p\. if needed\)\./gi, "एक साइकिल चालक $1 किमी $2 किमी/घंटा की गति से और फिर $3 किमी $4 किमी/घंटा की गति से सवारी करता है। औसत गति ज्ञात करें (यदि आवश्यक हो तो 2 दशमलव स्थानों तक)।");
    t = t.replace(/Convert ([\d\.]+) m\/s to km\/h\./gi, "$1 मीटर/सेकंड को किमी/घंटा में बदलें।");
    t = t.replace(/y is directly proportional to x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y, x के सीधे समानुपाती है। जब x = $1, तो y = $2। x = $3 होने पर y ज्ञात करें।");
    t = t.replace(/y is inversely proportional to x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y, x के व्युत्क्रमानुपाती है। जब x = $1, तो y = $2। x = $3 होने पर y ज्ञात करें।");
    t = t.replace(/y is directly proportional to x²\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y, x² के सीधे समानुपाती है। जब x = $1, तो y = $2। x = $3 होने पर y ज्ञात करें।");
    t = t.replace(/y is inversely proportional to √x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y, √x के व्युत्क्रमानुपाती है। जब x = $1, तो y = $2। x = $3 होने पर y ज्ञात करें।");
    t = t.replace(/An item is bought for \$([\d\.]+) and sold for \$([\d\.]+)\. Find the profit\./gi, "एक वस्तु $$1 में खरीदी जाती है और $$2 में बेची जाती है। लाभ ज्ञात करें।");
    t = t.replace(/Cost price = \$([\d\.]+), selling price = \$([\d\.]+)\. Find the profit percentage\./gi, "क्रय मूल्य = $$1, विक्रय मूल्य = $$2। लाभ प्रतिशत ज्ञात करें।");
    t = t.replace(/A shirt has a marked price of \$([\d\.]+)\. A ([\d\.]+)% discount is applied\. Find the selling price\./gi, "एक शर्ट का अंकित मूल्य $$1 है। $2% की छूट दी जाती है। विक्रय मूल्य ज्ञात करें।");
    t = t.replace(/Marked price is \$([\d\.]+)\. Successive discounts of ([\d\.]+)% and ([\d\.]+)% are applied\. Find the final price\./gi, "अंकित मूल्य $$1 है। $2% और $3% की क्रमिक छूट लागू की जाती है। अंतिम मूल्य ज्ञात करें।");
    t = t.replace(/Calculate the (Speed|Distance|Time) if (.*)\./gi, "यदि $2 हो तो $1 ज्ञात करें।");
    t = t.replace(/Expand and simplify (.*)/gi, "$1 का विस्तार और सरलीकरण करें");
    t = t.replace(/Find the roots of (.*)/gi, "$1 के मूल ज्ञात करें");
    t = t.replace(/Solve for (x|y|z):/gi, "$1 के लिए हल करें:");
    t = t.replace(/Factorise completely:/gi, "पूर्णतः गुणनखंडन करें:");
    t = t.replace(/Factorise:/gi, "गुणनखंडन करें:");
    t = t.replace(/Simplify the ratio (.*)/gi, "अनुपात $1 को सरल करें");
    t = t.replace(/Find the HCF of (.*)/gi, "$1 का म.स.प. (HCF) ज्ञात करें");
    t = t.replace(/Find the LCM of (.*)/gi, "$1 का ल.स.प. (LCM) ज्ञात करें");
    
    t = t.replace(/Find the area of a circle with radius (.*)/gi, "त्रिज्या $1 वाले वृत्त का क्षेत्रफल ज्ञात करें");
    t = t.replace(/Find the circumference of a circle with radius (.*)/gi, "त्रिज्या $1 वाले वृत्त की परिधि ज्ञात करें");

    t = t.replace(/Convert (.*) to (.*)/gi, "$1 को $2 में बदलें");
    t = t.replace(/What is (.*)\?/gi, "$1 क्या है?");
    t = t.replace(/Evaluate (.*)/gi, "$1 का मान ज्ञात करें");
    t = t.replace(/Calculate (.*)/gi, "$1 की गणना करें");
    t = t.replace(/Solve (.*)/gi, "$1 को हल करें");

    t = t.replace(/Speed/g, "गति");
    t = t.replace(/Distance/g, "दूरी");
    t = t.replace(/Time/g, "समय");
    t = t.replace(/Profit/g, "लाभ");
    t = t.replace(/Loss/g, "हानि");
    t = t.replace(/Solution:/g, "समाधान:");
    t = t.replace(/Explanation:/g, "व्याख्या:");
    t = t.replace(/Correct!/g, "सही!");
  } else if (locale === 'ta') {
    t = t.replace(/Round ([\d\.]+) to (\d+) decimal place(s)?\./gi, "$1 ஐ $2 தசம இடங்களுக்கு முழுமையாக்குங்கள்.");
    t = t.replace(/Round ([\d\.]+) to (\d+) significant figure(s)?\./gi, "$1 ஐ $2 முக்கிய இலக்கங்களுக்கு முழுமையாக்குங்கள்.");
    t = t.replace(/Find the probability of getting (.*) when rolling a fair six-sided die\./gi, "நியாயமான 6-பக்க பகடையை உருட்டும்போது $1 பெறுவதற்கான நிகழ்தகவைக் காண்க.");
    t = t.replace(/A bag contains (\d+) (.*) and (\d+) (.*)\./gi, "ஒரு பையில் $1 $2 மற்றும் $3 $4 உள்ளன.");
    t = t.replace(/A car travels at ([\d\.]+) km\/h for ([\d\.]+) hours\. How far does it travel \(in km\)\?/gi, "ஒரு கார் $1 கிமீ/மணி வேகத்தில் $2 மணிநேரம் பயணிக்கிறது. அது எவ்வளவு தூரம் பயணிக்கிறது (கிமீ-இல்)?");
    t = t.replace(/A train covers ([\d\.]+) km at ([\d\.]+) km\/h\. How long does the journey take \(in hours\)\?/gi, "ஒரு ரயில் $1 கிமீ தூரத்தை $2 கிமீ/மணி வேகத்தில் கடக்கிறது. பயணத்திற்கு எவ்வளவு நேரம் ஆகும் (மணிநேரத்தில்)?");
    t = t.replace(/A cyclist rides ([\d\.]+) km at ([\d\.]+) km\/h then ([\d\.]+) km at ([\d\.]+) km\/h\. Find the average speed \(to 2 d\.p\. if needed\)\./gi, "ஒரு சைக்கிள் ஓட்டுபவர் $1 கிமீ தூரத்தை $2 கிமீ/மணி வேகத்திலும், பின்னர் $3 கிமீ தூரத்தை $4 கிமீ/மணி வேகத்திலும் ஓட்டுகிறார். சராசரி வேகத்தைக் காண்க (தேவைப்பட்டால் 2 தசம இடங்களுக்கு).");
    t = t.replace(/Convert ([\d\.]+) m\/s to km\/h\./gi, "$1 மீ/வி ஐ கிமீ/மணி ஆக மாற்றுக.");
    t = t.replace(/y is directly proportional to x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y ஆனது x க்கு நேர்தகவில் உள்ளது. x = $1 ஆக இருக்கும்போது, y = $2. x = $3 ஆக இருக்கும்போது y-ஐக் காண்க.");
    t = t.replace(/y is inversely proportional to x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y ஆனது x க்கு எதிர்தகவில் உள்ளது. x = $1 ஆக இருக்கும்போது, y = $2. x = $3 ஆக இருக்கும்போது y-ஐக் காண்க.");
    t = t.replace(/y is directly proportional to x²\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y ஆனது x² க்கு நேர்தகவில் உள்ளது. x = $1 ஆக இருக்கும்போது, y = $2. x = $3 ஆக இருக்கும்போது y-ஐக் காண்க.");
    t = t.replace(/y is inversely proportional to √x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y ஆனது √x க்கு எதிர்தகவில் உள்ளது. x = $1 ஆக இருக்கும்போது, y = $2. x = $3 ஆக இருக்கும்போது y-ஐக் காண்க.");
    t = t.replace(/An item is bought for \$([\d\.]+) and sold for \$([\d\.]+)\. Find the profit\./gi, "ஒரு பொருள் $$1 க்கு வாங்கப்பட்டு $$2 க்கு விற்கப்படுகிறது. லாபத்தைக் காண்க.");
    t = t.replace(/Cost price = \$([\d\.]+), selling price = \$([\d\.]+)\. Find the profit percentage\./gi, "அடக்க விலை = $$1, விற்பனை விலை = $$2. லாப சதவீதத்தைக் காண்க.");
    t = t.replace(/A shirt has a marked price of \$([\d\.]+)\. A ([\d\.]+)% discount is applied\. Find the selling price\./gi, "ஒரு சட்டையின் குறிக்கப்பட்ட விலை $$1. $2% தள்ளுபடி வழங்கப்படுகிறது. விற்பனை விலையைக் காண்க.");
    t = t.replace(/Marked price is \$([\d\.]+)\. Successive discounts of ([\d\.]+)% and ([\d\.]+)% are applied\. Find the final price\./gi, "குறிக்கப்பட்ட விலை $$1. $2% மற்றும் $3% தொடர் தள்ளுபடிகள் வழங்கப்படுகின்றன. இறுதி விலையைக் காண்க.");
    t = t.replace(/Calculate the (Speed|Distance|Time) if (.*)\./gi, "$2 எனில் $1-ஐக் கணக்கிடுக.");
    t = t.replace(/Expand and simplify (.*)/gi, "$1 ஐ விரிவுபடுத்தி சுருக்குக");
    t = t.replace(/Find the roots of (.*)/gi, "$1 இன் மூலங்களைக் காண்க");
    t = t.replace(/Solve for (x|y|z):/gi, "$1 க்கான தீர்வு காண்க:");
    t = t.replace(/Factorise completely:/gi, "முழுமையாக காரணிப்படுத்துக:");
    t = t.replace(/Factorise:/gi, "காரணிப்படுத்துக:");
    t = t.replace(/Simplify the ratio (.*)/gi, "$1 என்ற விகிதத்தை சுருக்குக");
    t = t.replace(/Find the HCF of (.*)/gi, "$1 இன் மீ.பொ.வ (HCF) காண்க");
    t = t.replace(/Find the LCM of (.*)/gi, "$1 இன் மீ.சி.ம (LCM) காண்க");
    t = t.replace(/Find the area of a circle with radius (.*)/gi, "ஆரம் $1 கொண்ட வட்டத்தின் பரப்பளவைக் காண்க");
    t = t.replace(/Find the circumference of a circle with radius (.*)/gi, "ஆரம் $1 கொண்ட வட்டத்தின் சுற்றளவைக் காண்க");
    t = t.replace(/Convert (.*) to (.*)/gi, "$1 ஐ $2 ஆக மாற்றுக");
    t = t.replace(/What is (.*)\?/gi, "$1 என்றால் என்ன?");
    t = t.replace(/Evaluate (.*)/gi, "$1 இன் மதிப்பைக் காண்க");
    t = t.replace(/Calculate (.*)/gi, "$1 ஐக் கணக்கிடுக");
    t = t.replace(/Solve (.*)/gi, "$1 ஐத் தீர்க்க");
    t = t.replace(/Speed/g, "வேகம்");
    t = t.replace(/Distance/g, "தூரம்");
    t = t.replace(/Time/g, "நேரம்");
    t = t.replace(/Profit/g, "லாபம்");
    t = t.replace(/Loss/g, "நஷ்டம்");
    t = t.replace(/Solution:/g, "தீர்வு:");
    t = t.replace(/Explanation:/g, "விளக்கம்:");
    t = t.replace(/Correct!/g, "சரியானது!");
  } else if (locale === 'mr') {
    t = t.replace(/Round ([\d\.]+) to (\d+) decimal place(s)?\./gi, "$1 ला $2 दशांश स्थानांपर्यंत पूर्णांकित करा.");
    t = t.replace(/Round ([\d\.]+) to (\d+) significant figure(s)?\./gi, "$1 ला $2 सार्थ अंकांपर्यंत पूर्णांकित करा.");
    t = t.replace(/Find the probability of getting (.*) when rolling a fair six-sided die\./gi, "निष्पक्ष फासा टाकल्यावर $1 मिळण्याची संभाव्यता काढा.");
    t = t.replace(/A bag contains (\d+) (.*) and (\d+) (.*)\./gi, "एका बॅगमध्ये $1 $2 आणि $3 $4 आहेत.");
    t = t.replace(/A car travels at ([\d\.]+) km\/h for ([\d\.]+) hours\. How far does it travel \(in km\)\?/gi, "एक कार $1 किमी/तास वेगाने $2 तास प्रवास करते. ती किती दूर प्रवास करते (किमी मध्ये)?");
    t = t.replace(/A train covers ([\d\.]+) km at ([\d\.]+) km\/h\. How long does the journey take \(in hours\)\?/gi, "एक ट्रेन $1 किमी अंतर $2 किमी/तास वेगाने पार करते. प्रवासाला किती वेळ लागतो (तासांत)?");
    t = t.replace(/A cyclist rides ([\d\.]+) km at ([\d\.]+) km\/h then ([\d\.]+) km at ([\d\.]+) km\/h\. Find the average speed \(to 2 d\.p\. if needed\)\./gi, "एक सायकलस्वार $1 किमी $2 किमी/तास वेगाने आणि नंतर $3 किमी $4 किमी/तास वेगाने चालवतो. सरासरी वेग काढा (गरज असल्यास 2 दशांश स्थानांपर्यंत).");
    t = t.replace(/Convert ([\d\.]+) m\/s to km\/h\./gi, "$1 मी/से ला किमी/तास मध्ये रूपांतरित करा.");
    t = t.replace(/y is directly proportional to x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y हे x च्या समप्रमाणात आहे. जेव्हा x = $1, तेव्हा y = $2. जेव्हा x = $3 असेल तेव्हा y काढा.");
    t = t.replace(/y is inversely proportional to x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y हे x च्या व्यस्त प्रमाणात आहे. जेव्हा x = $1, तेव्हा y = $2. जेव्हा x = $3 असेल तेव्हा y काढा.");
    t = t.replace(/y is directly proportional to x²\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y हे x² च्या समप्रमाणात आहे. जेव्हा x = $1, तेव्हा y = $2. जेव्हा x = $3 असेल तेव्हा y काढा.");
    t = t.replace(/y is inversely proportional to √x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y हे √x च्या व्यस्त प्रमाणात आहे. जेव्हा x = $1, तेव्हा y = $2. जेव्हा x = $3 असेल तेव्हा y काढा.");
    t = t.replace(/An item is bought for \$([\d\.]+) and sold for \$([\d\.]+)\. Find the profit\./gi, "एक वस्तू $$1 ला खरेदी केली आणि $$2 ला विकली. नफा काढा.");
    t = t.replace(/Cost price = \$([\d\.]+), selling price = \$([\d\.]+)\. Find the profit percentage\./gi, "खरेदी किंमत = $$1, विक्री किंमत = $$2. शेकडा नफा काढा.");
    t = t.replace(/A shirt has a marked price of \$([\d\.]+)\. A ([\d\.]+)% discount is applied\. Find the selling price\./gi, "एका शर्टची छापील किंमत $$1 आहे. $2% सूट दिली जाते. विक्री किंमत काढा.");
    t = t.replace(/Marked price is \$([\d\.]+)\. Successive discounts of ([\d\.]+)% and ([\d\.]+)% are applied\. Find the final price\./gi, "छापील किंमत $$1 आहे. अनुक्रमे $2% आणि $3% सलग सूट दिली जाते. अंतिम किंमत काढा.");
    t = t.replace(/Calculate the (Speed|Distance|Time) if (.*)\./gi, "जर $2 असेल तर $1 काढा.");
    t = t.replace(/Expand and simplify (.*)/gi, "$1 चा विस्तार आणि सुलभ करा");
    t = t.replace(/Find the roots of (.*)/gi, "$1 ची मुळे काढा");
    t = t.replace(/Solve for (x|y|z):/gi, "$1 साठी सोडवा:");
    t = t.replace(/Factorise completely:/gi, "पूर्णपणे अवयव पाडा:");
    t = t.replace(/Factorise:/gi, "अवयव पाडा:");
    t = t.replace(/Simplify the ratio (.*)/gi, "$1 हे गुणोत्तर सुलभ करा");
    t = t.replace(/Find the HCF of (.*)/gi, "$1 चा मसावी (HCF) काढा");
    t = t.replace(/Find the LCM of (.*)/gi, "$1 चा लसावी (LCM) काढा");
    t = t.replace(/Find the area of a circle with radius (.*)/gi, "त्रिज्या $1 असलेल्या वर्तुळाचे क्षेत्रफळ काढा");
    t = t.replace(/Find the circumference of a circle with radius (.*)/gi, "त्रिज्या $1 असलेल्या वर्तुळाचा परिघ काढा");
    t = t.replace(/Convert (.*) to (.*)/gi, "$1 ला $2 मध्ये रूपांतरित करा");
    t = t.replace(/What is (.*)\?/gi, "$1 म्हणजे काय?");
    t = t.replace(/Evaluate (.*)/gi, "$1 चे मूल्य काढा");
    t = t.replace(/Calculate (.*)/gi, "$1 ची गणना करा");
    t = t.replace(/Solve (.*)/gi, "$1 सोडवा");
    t = t.replace(/Speed/g, "वेग");
    t = t.replace(/Distance/g, "अंतर");
    t = t.replace(/Time/g, "वेळ");
    t = t.replace(/Profit/g, "नफा");
    t = t.replace(/Loss/g, "तोटा");
    t = t.replace(/Solution:/g, "उकल:");
    t = t.replace(/Explanation:/g, "स्पष्टीकरण:");
    t = t.replace(/Correct!/g, "बरोबर!");
  } else if (locale === 'te') {
    t = t.replace(/Round ([\d\.]+) to (\d+) decimal place(s)?\./gi, "$1 ను $2 దశాంశ స్థానాలకు రౌండ్ చేయండి.");
    t = t.replace(/Round ([\d\.]+) to (\d+) significant figure(s)?\./gi, "$1 ను $2 ముఖ్యమైన అంకెలకు రౌండ్ చేయండి.");
    t = t.replace(/Find the probability of getting (.*) when rolling a fair six-sided die\./gi, "న్యాయమైన 6-వైపుల పాచికను వేసినప్పుడు $1 పొందే సంభావ్యతను కనుగొనండి.");
    t = t.replace(/A bag contains (\d+) (.*) and (\d+) (.*)\./gi, "ఒక బ్యాగ్‌లో $1 $2 మరియు $3 $4 ఉన్నాయి.");
    t = t.replace(/A car travels at ([\d\.]+) km\/h for ([\d\.]+) hours\. How far does it travel \(in km\)\?/gi, "ఒక కారు $1 కిమీ/గంట వేగంతో $2 గంటలు ప్రయాణిస్తుంది. అది ఎంత దూరం ప్రయాణిస్తుంది (కిమీలలో)?");
    t = t.replace(/A train covers ([\d\.]+) km at ([\d\.]+) km\/h\. How long does the journey take \(in hours\)\?/gi, "ఒక రైలు $1 కిమీ దూరాన్ని $2 కిమీ/గంట వేగంతో ప్రయాణిస్తుంది. ప్రయాణానికి ఎంత సమయం పడుతుంది (గంటలలో)?");
    t = t.replace(/A cyclist rides ([\d\.]+) km at ([\d\.]+) km\/h then ([\d\.]+) km at ([\d\.]+) km\/h\. Find the average speed \(to 2 d\.p\. if needed\)\./gi, "ఒక సైక్లిస్ట్ $1 కిమీ దూరాన్ని $2 కిమీ/గంట వేగంతో మరియు తరువాత $3 కిమీ దూరాన్ని $4 కిమీ/గంట వేగంతో నడుపుతాడు. సగటు వేగాన్ని కనుగొనండి (అవసరమైతే 2 దశాంశ స్థానాలకు).");
    t = t.replace(/Convert ([\d\.]+) m\/s to km\/h\./gi, "$1 మీ/సెకనును కిమీ/గంటకు మార్చండి.");
    t = t.replace(/y is directly proportional to x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y అనేది x కి అనులోమానుపాతంలో ఉంటుంది. x = $1 అయినప్పుడు, y = $2. x = $3 అయినప్పుడు y ని కనుగొనండి.");
    t = t.replace(/y is inversely proportional to x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y అనేది x కి విలోమానుపాతంలో ఉంటుంది. x = $1 అయినప్పుడు, y = $2. x = $3 అయినప్పుడు y ని కనుగొనండి.");
    t = t.replace(/y is directly proportional to x²\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y అనేది x² కి అనులోమానుపాతంలో ఉంటుంది. x = $1 అయినప్పుడు, y = $2. x = $3 అయినప్పుడు y ని కనుగొనండి.");
    t = t.replace(/y is inversely proportional to √x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y అనేది √x కి విలోమానుపాతంలో ఉంటుంది. x = $1 అయినప్పుడు, y = $2. x = $3 అయినప్పుడు y ని కనుగొనండి.");
    t = t.replace(/An item is bought for \$([\d\.]+) and sold for \$([\d\.]+)\. Find the profit\./gi, "ఒక వస్తువు $$1 కి కొనబడి $$2 కి విక్రయించబడింది. లాభాన్ని కనుగొనండి.");
    t = t.replace(/Cost price = \$([\d\.]+), selling price = \$([\d\.]+)\. Find the profit percentage\./gi, "కొన్న వెల = $$1, అమ్మిన వెల = $$2. లాభ శాతాన్ని కనుగొనండి.");
    t = t.replace(/A shirt has a marked price of \$([\d\.]+)\. A ([\d\.]+)% discount is applied\. Find the selling price\./gi, "ఒక చొక్కా ప్రకటించిన వెల $$1. $2% తగ్గింపు వర్తించబడింది. అమ్మిన వెలను కనుగొనండి.");
    t = t.replace(/Marked price is \$([\d\.]+)\. Successive discounts of ([\d\.]+)% and ([\d\.]+)% are applied\. Find the final price\./gi, "ప్రకటించిన వెల $$1. వరుసగా $2% మరియు $3% తగ్గింపులు వర్తించబడతాయి. తుది వెలను కనుగొనండి.");
    t = t.replace(/Calculate the (Speed|Distance|Time) if (.*)\./gi, "$2 అయితే $1 కనుగొనండి.");
    t = t.replace(/Expand and simplify (.*)/gi, "$1 ను విస్తరించి సూక్ష్మీకరించండి");
    t = t.replace(/Find the roots of (.*)/gi, "$1 యొక్క మూలాలను కనుగొనండి");
    t = t.replace(/Solve for (x|y|z):/gi, "$1 కోసం పరిష్కరించండి:");
    t = t.replace(/Factorise completely:/gi, "పూర్తిగా కారణాంకాలుగా విభజించండి:");
    t = t.replace(/Factorise:/gi, "కారణాంకాలుగా విభజించండి:");
    t = t.replace(/Simplify the ratio (.*)/gi, "$1 నిష్పత్తిని సూక్ష్మీకరించండి");
    t = t.replace(/Find the HCF of (.*)/gi, "$1 యొక్క గ.సా.భా (HCF) కనుగొనండి");
    t = t.replace(/Find the LCM of (.*)/gi, "$1 యొక్క క.సా.గు (LCM) కనుగొనండి");
    t = t.replace(/Find the area of a circle with radius (.*)/gi, "వ్యాసార్థం $1 కలిగిన వృత్తం వైశాల్యాన్ని కనుగొనండి");
    t = t.replace(/Find the circumference of a circle with radius (.*)/gi, "వ్యాసార్థం $1 కలిగిన వృత్తం చుట్టుకొలతను కనుగొనండి");
    t = t.replace(/Convert (.*) to (.*)/gi, "$1 ను $2 కి మార్చండి");
    t = t.replace(/What is (.*)\?/gi, "$1 అంటే ఏమిటి?");
    t = t.replace(/Evaluate (.*)/gi, "$1 ను లెక్కించండి");
    t = t.replace(/Calculate (.*)/gi, "$1 కనుగొనండి");
    t = t.replace(/Solve (.*)/gi, "$1 పరిష్కరించండి");
    t = t.replace(/Speed/g, "వేగం");
    t = t.replace(/Distance/g, "దూరం");
    t = t.replace(/Time/g, "సమయం");
    t = t.replace(/Profit/g, "లాభం");
    t = t.replace(/Loss/g, "నష్టం");
    t = t.replace(/Solution:/g, "పరిష్కారం:");
    t = t.replace(/Explanation:/g, "వివరణ:");
    t = t.replace(/Correct!/g, "సరైనది!");
  } else if (locale === 'bn') {
    t = t.replace(/Round ([\d\.]+) to (\d+) decimal place(s)?\./gi, "$1 কে $2 দশমিক স্থান পর্যন্ত রাউণ্ড করুন।");
    t = t.replace(/Round ([\d\.]+) to (\d+) significant figure(s)?\./gi, "$1 কে $2 তাৎপর্যপূর্ণ অঙ্ক পর্যন্ত রাউণ্ড করুন।");
    t = t.replace(/Find the probability of getting (.*) when rolling a fair six-sided die\./gi, "ন্যায্য ৬-পার্শ্বযুক্ত ছক্কা ছুঁড়লে $1 পাওয়ার সম্ভাবনা খুঁজুন।");
    t = t.replace(/A bag contains (\d+) (.*) and (\d+) (.*)\./gi, "একটি ব্যাগে $1 $2 এবং $3 $4 রয়েছে।");
    t = t.replace(/A car travels at ([\d\.]+) km\/h for ([\d\.]+) hours\. How far does it travel \(in km\)\?/gi, "একটি গাড়ি $1 কিমি/ঘন্টা বেগে $2 ঘন্টা ভ্রমণ করে। এটি কত দূরত্ব অতিক্রম করে (কিমি-তে)?");
    t = t.replace(/A train covers ([\d\.]+) km at ([\d\.]+) km\/h\. How long does the journey take \(in hours\)\?/gi, "একটি ট্রেন $1 কিমি দূরত্ব $2 কিমি/ঘন্টা বেগে অতিক্রম করে। যাত্রায় কত সময় লাগে (ঘন্টায়)?");
    t = t.replace(/A cyclist rides ([\d\.]+) km at ([\d\.]+) km\/h then ([\d\.]+) km at ([\d\.]+) km\/h\. Find the average speed \(to 2 d\.p\. if needed\)\./gi, "একজন সাইকেল চালক $1 কিমি $2 কিমি/ঘন্টা বেগে এবং পরে $3 কিমি $4 কিমি/ঘন্টা বেগে চালান। গড় গতি খুঁজুন (প্রয়োজন হলে ২ দশমিক স্থান পর্যন্ত)।");
    t = t.replace(/Convert ([\d\.]+) m\/s to km\/h\./gi, "$1 মি/সে কে কিমি/ঘন্টায় রূপান্তর করুন।");
    t = t.replace(/y is directly proportional to x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y হল x এর সমানুপাতিক। যখন x = $1, তখন y = $2। x = $3 হলে y খুঁজুন।");
    t = t.replace(/y is inversely proportional to x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y হল x এর ব্যস্তানুপাতিক। যখন x = $1, তখন y = $2। x = $3 হলে y খুঁজুন।");
    t = t.replace(/y is directly proportional to x²\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y হল x² এর সমানুপাতিক। যখন x = $1, তখন y = $2। x = $3 হলে y খুঁজুন।");
    t = t.replace(/y is inversely proportional to √x\. When x = ([\d\.]+), y = ([\d\.]+)\. Find y when x = ([\d\.]+)\./gi, "y হল √x এর ব্যস্তানুপাতিক। যখন x = $1, তখন y = $2। x = $3 হলে y খুঁজুন।");
    t = t.replace(/An item is bought for \$([\d\.]+) and sold for \$([\d\.]+)\. Find the profit\./gi, "একটি জিনিস $$1 এ কেনা হয়েছে এবং $$2 এ বিক্রি করা হয়েছে। লাভ খুঁজুন।");
    t = t.replace(/Cost price = \$([\d\.]+), selling price = \$([\d\.]+)\. Find the profit percentage\./gi, "ক্রয় মূল্য = $$1, বিক্রয় মূল্য = $$2। লাভের শতাংশ খুঁজুন।");
    t = t.replace(/A shirt has a marked price of \$([\d\.]+)\. A ([\d\.]+)% discount is applied\. Find the selling price\./gi, "একটি শার্টের চিহ্নিত মূল্য $$1। $2% ছাড় দেওয়া হয়েছে। বিক্রয় মূল্য খুঁজুন।");
    t = t.replace(/Marked price is \$([\d\.]+)\. Successive discounts of ([\d\.]+)% and ([\d\.]+)% are applied\. Find the final price\./gi, "চিহ্নিত মূল্য $$1। পরপর $2% এবং $3% ছাড় দেওয়া হয়েছে। চূড়ান্ত মূল্য খুঁজুন।");
    t = t.replace(/Calculate the (Speed|Distance|Time) if (.*)\./gi, "$2 হলে $1 গণনা করুন।");
    t = t.replace(/Expand and simplify (.*)/gi, "$1 প্রসারিত এবং সরল করুন");
    t = t.replace(/Find the roots of (.*)/gi, "$1 এর মূলগুলি খুঁজুন");
    t = t.replace(/Solve for (x|y|z):/gi, "$1 এর জন্য সমাধান করুন:");
    t = t.replace(/Factorise completely:/gi, "সম্পূর্ণরূপে উৎপাদকে বিশ্লেষণ করুন:");
    t = t.replace(/Factorise:/gi, "উৎপাদকে বিশ্লেষণ করুন:");
    t = t.replace(/Simplify the ratio (.*)/gi, "$1 অনুপাত সরল করুন");
    t = t.replace(/Find the HCF of (.*)/gi, "$1 এর গ.সা.গু (HCF) খুঁজুন");
    t = t.replace(/Find the LCM of (.*)/gi, "$1 এর ল.সা.গু (LCM) খুঁজুন");
    t = t.replace(/Find the area of a circle with radius (.*)/gi, "ব্যাসার্ধ $1 বিশিষ্ট বৃত্তের ক্ষেত্রফল খুঁজুন");
    t = t.replace(/Find the circumference of a circle with radius (.*)/gi, "ব্যাসার্ধ $1 বিশিষ্ট বৃত্তের পরিধি খুঁজুন");
    t = t.replace(/Convert (.*) to (.*)/gi, "$1 কে $2 এ রূপান্তর করুন");
    t = t.replace(/What is (.*)\?/gi, "$1 কী?");
    t = t.replace(/Evaluate (.*)/gi, "$1 মূল্যায়ন করুন");
    t = t.replace(/Calculate (.*)/gi, "$1 গণনা করুন");
    t = t.replace(/Solve (.*)/gi, "$1 সমাধান করুন");
    t = t.replace(/Speed/g, "গতি");
    t = t.replace(/Distance/g, "দূরত্ব");
    t = t.replace(/Time/g, "সময়");
    t = t.replace(/Profit/g, "লাভ");
    t = t.replace(/Loss/g, "ক্ষতি");
    t = t.replace(/Solution:/g, "সমাধান:");
    t = t.replace(/Explanation:/g, "ব্যাখ্যা:");
    t = t.replace(/Correct!/g, "সঠিক!");
  }

  return t;
}
